name: Docker Image CI

on:
  push:
    branches: ['main']
    paths: ['src/**']
       
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Set Image tag
      id: set-image-tag
      shell: bash
      run: |
        echo "::set-output name=image_tag::$(echo ${{ github.sha }} | cut -c1-12)".

    - name: Build Docker image
      env:
        IMAGE_TAG: ${{ steps.set-image-tag.outputs.image_tag }}
      run: |
        docker build . --file Dockerfile --tag juanwigg/nasdaq-index-red:$IMAGE_TAG
        docker tag juanwigg/nasdaq-index-red:$IMAGE_TAG juanwigg/nasdaq-index-red:latest
      
    - name: Push Docker image
      env:
        IMAGE_TAG: ${{ steps.set-image-tag.outputs.image_tag }}
      run: |
        docker push juanwigg/nasdaq-index-red:$IMAGE_TAG
        docker push juanwigg/nasdaq-index-red:latest